# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliacion', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.CharField(blank=True, max_length=36, verbose_name='Cita')),
                ('medico', models.CharField(max_length=36)),
                ('eess', models.CharField(max_length=36)),
                ('ups', models.CharField(blank=True, max_length=10, verbose_name='UPS')),
                ('fecha', models.DateField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Paciente', verbose_name='Atención')),
            ],
            options={
                'ordering': ('-fecha',),
                'verbose_name_plural': 'Atenciones',
            },
        ),
        migrations.CreateModel(
            name='AtencionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('codigo', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[(1, 'CONTROL por EMD'), (2, 'CONTROL LABORATORIO')])),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AtencionControlXFrecuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.AtencionControl')),
            ],
            options={
                'verbose_name': 'Relación Control por Frecuencia',
                'verbose_name_plural': 'Relación Control por Frecuencia',
            },
        ),
        migrations.CreateModel(
            name='AtencionDescarteCoinfeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cie', models.CharField(blank=True, max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=500, verbose_name='Observación')),
                ('fecha_descarte', models.DateField(blank=True, null=True)),
                ('infeccion', models.IntegerField()),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cie', models.CharField(blank=True, max_length=50)),
                ('estadio', models.CharField(choices=[('', '---'), ('1', 'Estadío 1'), ('2', 'Estadío 2 (Avanzado)'), ('3', 'Estadío 3 (SIDA)'), ('4', 'Desconocido')], default='1', max_length=2, verbose_name='Estadío')),
                ('tipo_dx', models.CharField(max_length=2, verbose_name='Tipo de Dx')),
                ('indicacion', models.CharField(max_length=500, null=True, verbose_name='Indicación')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionExamenAuxiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=10)),
                ('imagen_fecha', models.DateField(blank=True, null=True)),
                ('laboratorio', models.CharField(max_length=10)),
                ('laboratorio_fecha', models.DateField(blank=True, null=True)),
                ('procedimiento', models.CharField(max_length=10)),
                ('procedimiento_fecha', models.DateField(blank=True, null=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
            options={
                'verbose_name_plural': 'Exámenes Auxiliar',
            },
        ),
        migrations.CreateModel(
            name='AtencionExamenFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, default='1', max_length=2, verbose_name='Estado')),
                ('obs', models.CharField(blank=True, max_length=500, verbose_name='Observación')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionFrecuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10, verbose_name='Descripción')),
                ('tiempo_dias', models.IntegerField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='AtencionFrecuenciaControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.UUIDField(db_index=True, verbose_name='Paciente')),
                ('estado', models.IntegerField(default=1)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionFrecuenciaControlDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('nueva_fecha_programada', models.DateField(null=True)),
                ('fecha_atencion', models.DateField(null=True)),
                ('check', models.IntegerField(default=0)),
                ('atencion_frecuencia_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.AtencionFrecuenciaControl')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.AtencionControl')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.AtencionFrecuencia')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionGestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fur', models.DateField(blank=True, null=True, verbose_name='FUR')),
                ('fpp', models.DateField(blank=True, null=True, verbose_name='FPP')),
                ('edad', models.PositiveSmallIntegerField(default=1, verbose_name='Edad Gestacional')),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestacion_atencion', to='atencion.Atencion', verbose_name='Atención')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='Descripción de la RAM')),
                ('fg_presenta_ram', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fg_gravedad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], default=1, verbose_name='Gravedad')),
                ('descripcion_gravedad', models.CharField(blank=True, max_length=500, verbose_name='Cuando RAM es grave')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Medicamento', verbose_name='Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionTerapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuvo_terapia', models.BooleanField(default=True)),
                ('terapia', models.IntegerField(choices=[(1, 'Rifapentina más Isoniacida 1 vez por semana durante 3 meses'), (2, 'Isoniacida más Rifampicina diario durante 3 meses'), (3, 'Isoniacida diaria durante 9 meses*')], default=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('razon', models.TextField(blank=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dia', models.PositiveSmallIntegerField(default=1, verbose_name='N° a suministrar por dia')),
                ('nro_dias', models.PositiveSmallIntegerField(default=1, verbose_name='N° de dias')),
                ('indicacion', models.CharField(blank=True, max_length=500, verbose_name='Indicación')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('suspendido', 'Suspendido'), ('culmiado', 'Culminado')], default='en_curso', max_length=150, verbose_name='Estado del tratamiento')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento_trat', to='medicamentos.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.CharField(max_length=500, null=True, verbose_name='Anamnesis')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Peso')),
                ('talla', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Talla')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Temp')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='IMG')),
                ('frecuencia_cardiaca', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='FC')),
                ('frecuencia_respiratoria', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='FR')),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
        ),
        migrations.AddField(
            model_name='atencionexamenfisico',
            name='examen_fisico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.ExamenFisico', verbose_name='Exámen Físico'),
        ),
        migrations.AddField(
            model_name='atencioncontrolxfrecuencia',
            name='frecuencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.AtencionFrecuencia'),
        ),
        migrations.AlterUniqueTogether(
            name='atenciontratamiento',
            unique_together=set([('atencion', 'medicamento')]),
        ),
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together=set([('eess', 'medico', 'paciente', 'cita', 'ups', 'fecha')]),
        ),
    ]
