# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionexamenauxiliar',
            name='imagen',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='atencionexamenauxiliar',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='atencionexamenauxiliar',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
