# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0002_auto_20170822_0903'),
        ('atencion', '0004_auto_20170828_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='cita_uuid',
            field=models.UUIDField(null=True, verbose_name='Cita'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='codigo_eess',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='estado_atencion',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Atendido'), (3, 'Ausente')], default=1),
        ),
        migrations.AddField(
            model_name='atencion',
            name='estado_cita',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmada'), (3, 'Atendido'), (4, 'Cancelado'), (5, 'Finalizado'), (6, 'Ausente'), (7, 'Reprogramado')], default=1),
        ),
        migrations.AddField(
            model_name='atencion',
            name='id_financiador',
            field=models.CharField(choices=[('0', 'NO SE CONOCE'), ('1', 'USUARIO'), ('2', 'SIS'), ('3', 'ESSALUD'), ('4', 'S.O.A.T'), ('5', 'SANIDAD F.A.P'), ('6', 'SANIDAD NAVAL'), ('7', 'SANIDAD EP'), ('8', 'SANIDAD PNP'), ('9', 'PRIVADOS'), ('10', 'OTROS'), ('11', 'EXONERADO')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='atencion',
            name='nombre_eess',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='nombre_ups',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nombre UPS'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='regimen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tipo_atencion',
            field=models.IntegerField(choices=[(1, 'Cita'), (2, 'Demanda')], default=2),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tipo_seguro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tipo_seguro_descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='atencion',
            unique_together=set([('eess', 'medico', 'paciente', 'cita_uuid', 'ups', 'fecha')]),
        ),
    ]
