# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0003_auto_20171024_1727'),
        ('atencion', '0006_atencion_tipo_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='lugar_abordaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afiliacion.ATLugarAbordaje', verbose_name='Atención lugar de Abordaje'),
        ),
    ]
