# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0007_atencion_lugar_abordaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_egreso', models.IntegerField(choices=[(1, 'Abandono'), (2, 'Derivación'), (3, 'Fallecimiento')])),
                ('numero_episodio', models.IntegerField(blank=True, choices=[(1, '1er episodio'), (2, '2do episodio'), (3, '3er episodio')], null=True)),
                ('lugar_fallecimiento', models.IntegerField(blank=True, choices=[(1, 'En el EESS'), (2, 'Otro EESS'), (3, 'En el domicilio'), (4, 'Otro')], null=True)),
                ('fecha_egreso', models.DateField()),
                ('causa_fallecimiento', models.TextField(blank=True, verbose_name='Causa de Fallecimiento')),
                ('creator', models.CharField(max_length=20)),
                ('modifier', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='atencion.Atencion')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name_plural': 'Egresos',
                'verbose_name': 'Egreso',
            },
        ),
    ]
