# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cie', models.CharField(blank=True, max_length=50)),
                ('obs', models.TextField(blank=True)),
                ('fecha_dx', models.DateField()),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentePersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cie', models.CharField(blank=True, max_length=50)),
                ('fecha_dx', models.DateField()),
                ('obs', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedenteTerapiaAntirretroviral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('obs', models.CharField(max_length=500, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-fecha_inicio',),
            },
        ),
        migrations.CreateModel(
            name='AntecedenteTerapiaPreventiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_terapia_tub', models.BooleanField(default=False)),
                ('razon_cambio_tub', models.CharField(blank=True, max_length=500)),
                ('fecha_inicio_tub', models.DateField(null=True)),
                ('tiene_terapia_pne', models.BooleanField(default=False)),
                ('razon_cambio_pne', models.CharField(blank=True, max_length=500)),
                ('fecha_inicio_pne', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedenteVacunaRecibida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_dosis', models.PositiveSmallIntegerField(default=1, verbose_name='Dosis')),
                ('fecha_aplicacion', models.DateField(null=True, verbose_name='Fecha aplicación')),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
