# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antecedente', '0001_initial'),
        ('atencion', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentevacunarecibida',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_familiar_vacuna', to='atencion.Atencion', verbose_name='Atención'),
        ),
        migrations.AddField(
            model_name='antecedentevacunarecibida',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antecedente.Vacunas', verbose_name='Vacuna'),
        ),
        migrations.AddField(
            model_name='antecedenteterapiapreventiva',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_familiar_preventiva', to='atencion.Atencion', verbose_name='Atención'),
        ),
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_familiar_antirretroviral', to='atencion.Atencion', verbose_name='Atención'),
        ),
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='medicamento1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento1', to='medicamentos.Medicamento'),
        ),
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='medicamento2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento2', to='medicamentos.Medicamento'),
        ),
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='medicamento3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamento3', to='medicamentos.Medicamento'),
        ),
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='medicamento4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamento4', to='medicamentos.Medicamento'),
        ),
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='medicamento5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamento5', to='medicamentos.Medicamento'),
        ),
        migrations.AddField(
            model_name='antecedentepersonal',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_personal_atencion', to='atencion.Atencion', verbose_name='Atención'),
        ),
        migrations.AddField(
            model_name='antecedentepersonal',
            name='tipo_enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antecedente.TipoEnfermedad', verbose_name='Tipo de Enfermedad'),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_familiar_atencion', to='atencion.Atencion', verbose_name='Atención'),
        ),
        migrations.AddField(
            model_name='antecedentefamiliar',
            name='parentesco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='antecedente.Parentesco'),
        ),
    ]
