# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecedente', '0002_auto_20170803_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='antecedenteterapiaantirretroviral',
            name='esquema',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vacunas',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
