# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atencion', '0001_initial'),
        ('afiliacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consejeria', models.IntegerField(choices=[(0, 'Previa'), (1, 'Post')], default=0)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención')),
            ],
            options={
                'ordering': ('fecha_registro',),
            },
        ),
        migrations.CreateModel(
            name='ConsejeriaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_transmision', models.CharField(blank=True, max_length=250)),
                ('antecedentes', models.CharField(blank=True, choices=[('RSVARON', 'RS con varones'), ('RSBI', 'RS con ambos sexos'), ('CONTRA', 'Contrasexual'), ('DESCONOCIDO', 'Desconocido')], max_length=250)),
                ('tipo_transmision', models.CharField(blank=True, choices=[('HETERO', 'Heterosexual'), ('HOMO', 'Homosexual'), ('BI', 'Bisexual'), ('NODETERMINADO', 'No determinado'), ('TRANSFUSION', 'Transfusión de sangre y/o derivados'), ('UDI', 'Compartir agujas/UDI'), ('ACCIDENTE', 'Accidente con material contaminado'), ('TRANSPLANTE', 'Transplante de órganos ó tejidos')], max_length=250)),
                ('nro_parejas', models.IntegerField(default=1, null=True)),
                ('uso_preservativo', models.BooleanField(default=False)),
                ('consejeria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consejeria.Consejeria', verbose_name='Consejeria')),
            ],
        ),
        migrations.CreateModel(
            name='ConsejeriaPre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consejeria_previa', models.BooleanField(default=False, verbose_name='¿Recibio Consejeria Previa?')),
                ('esta_consentido', models.BooleanField(default=False, verbose_name='Firmar Consentimiento Informado')),
                ('validacion', models.TextField(blank=True)),
                ('consejeria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consejeria.Consejeria', verbose_name='Consejeria')),
                ('tipo_poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Poblacion', verbose_name='Tipo de Poblacion')),
            ],
            options={
                'ordering': ('consejeria__fecha_registro',),
            },
        ),
    ]
