# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consejeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consejeria',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Atencion', verbose_name='Atención'),
        ),
    ]
