# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consejeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.UUIDField(db_index=True, verbose_name='Paciente')),
                ('cpt', models.CharField(blank=True, max_length=50)),
                ('personal_salud', models.CharField(max_length=100, verbose_name='Personal de Salud')),
                ('eess', models.CharField(max_length=15, verbose_name='Establecimiento')),
                ('estado', models.CharField(choices=[('1', 'Solicitado'), ('2', 'Con Resultado'), ('3', 'Resultado Parcial'), ('4', 'Nueva Muestra')], default='1', max_length=1)),
                ('observaciones', models.CharField(blank=True, max_length=500)),
                ('fecha_prueba', models.DateField(blank=True, null=True)),
                ('consejeria_pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consejeria.Consejeria')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Examen')),
            ],
            options={
                'ordering': ('-fecha_prueba',),
            },
        ),
        migrations.CreateModel(
            name='ExamenResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=20, verbose_name='Resultado')),
                ('nro_prueba', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de prueba')),
                ('nro_muestra', models.CharField(blank=True, max_length=30, verbose_name='Número de muestra')),
                ('fecha_resultado', models.DateField(blank=True, null=True, verbose_name='Fecha de resultado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('laboratorio_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Examen', verbose_name='Exámen')),
            ],
        ),
    ]
