# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='meta',
        ),
        migrations.AddField(
            model_name='examen',
            name='codigo_muestra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='examen',
            name='hora_solicitud',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='cantidad_condones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='cantidad_lubricantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='codigo_eess',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='fecha_cita',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='ficha_informativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='nombre_eess',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='post_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='refiere_eess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examenresultado',
            name='repite_prueba',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examen',
            name='personal_salud',
            field=models.CharField(max_length=100, null=True, verbose_name='Personal de Salud'),
        ),
        migrations.AlterField(
            model_name='examenresultado',
            name='resultado',
            field=models.CharField(choices=[('REACTIVO', 'Reactivo'), ('NO REACTIVO', 'No Reactivo'), ('INDETERMINADO', 'Indeterminado')], max_length=10),
        ),
    ]
