# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_auto_20171024_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenresultado',
            name='resultado',
            field=models.CharField(choices=[('REACTIVO', 'Reactivo'), ('NO REACTIVO', 'No Reactivo'), ('INDETERMINADO', 'Indeterminado')], max_length=30),
        ),
    ]
