# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_auto_20171025_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenresultado',
            name='laboratorio_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='laboratorio.Examen', verbose_name='Exámen'),
        ),
    ]
