# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esquema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('primera_linea', 'Primera Línea'), ('de_rescate', 'De Rescate'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo')),
                ('etapa_crecimiento', models.IntegerField(blank=True, choices=[(0, 'Niño'), (1, 'Adulto')], null=True)),
                ('n_meses', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Meses')),
            ],
            options={
                'ordering': ('descripcion',),
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentación')),
                ('concentracion', models.CharField(max_length=100, verbose_name='Concentracion')),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Abreviatura')),
                ('targa', models.BooleanField(default=False, verbose_name='Usado en tratamiento Targa')),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.AddField(
            model_name='esquema',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='medicamentos.Medicamento'),
        ),
    ]
