# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEstablecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_renipres', models.CharField(max_length=8, unique=True, verbose_name='Código Renipres')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('ubigeo', models.CharField(blank=True, max_length=8, null=True, verbose_name='ubigeo')),
                ('categoria_cod', models.CharField(max_length=10, null=True)),
                ('sector_codigo', models.IntegerField(null=True)),
                ('diresa', models.IntegerField(null=True)),
                ('red', models.IntegerField(null=True)),
                ('cod_red', models.CharField(max_length=2, null=True)),
                ('microred', models.IntegerField(null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
                ('nombre_diresa', models.CharField(max_length=150, null=True, verbose_name='Nombre DISA/DIRESA')),
                ('nombre_red', models.CharField(max_length=150, null=True, verbose_name='Nombre Red')),
                ('nombre_microred', models.CharField(max_length=150, null=True, verbose_name='Nombre Microred')),
                ('nombre_sector', models.CharField(max_length=150, null=True, verbose_name='Nombre Sector')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='HCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hce', models.CharField(blank=True, max_length=12, null=True, verbose_name='Nº de Historia Clínica')),
                ('archivo_clinico', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nº Archivo Clinico')),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.CatalogoEstablecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteContactoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_phr_familiar', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('00', 'NO SE CONOCE'), ('01', 'DNI/LE'), ('02', 'LM/BO'), ('03', 'CARNET DE EXTRAJERIA'), ('04', 'ACTA DE NACIMIENTO'), ('06', 'PASAPORTE'), ('07', 'DI DEL EXTRANJERO')], max_length=2, null=True, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=12, verbose_name='Nº de documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(blank=True, choices=[('2', 'Femenino'), ('1', 'Masculino')], max_length=2, null=True, verbose_name='Sexo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=9, null=True, verbose_name='Celular')),
                ('correo', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Correo electrónico')),
                ('parentesco', models.CharField(blank=True, choices=[('1', 'Padre'), ('2', 'Madre'), ('3', 'Hijo'), ('4', 'Hija'), ('5', 'Esposo'), ('6', 'Esposa')], max_length=2, null=True, verbose_name='Parentesco')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='PacienteFinanciador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_afiliacion', models.CharField(max_length=15, verbose_name='Nº de Afiliacion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo_seguro', models.CharField(blank=True, choices=[('0', 'NO SE CONOCE'), ('1', 'USUARIO'), ('2', 'SIS'), ('3', 'ESSALUD'), ('4', 'S.O.A.T'), ('5', 'SANIDAD F.A.P'), ('6', 'SANIDAD NAVAL'), ('7', 'SANIDAD EP'), ('8', 'SANIDAD PNP'), ('9', 'PRIVADOS'), ('10', 'OTROS'), ('11', 'EXONERADO')], max_length=2, null=True, verbose_name='Tipo Seguro')),
                ('regimen', models.CharField(blank=True, choices=[(1, 'Subsidiado'), (2, 'Semi-Contributivo'), (4, 'Componente SemiSubsidiado')], max_length=2, null=True, verbose_name='Regimen')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='centro_poblado_actual',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Centro Poblado Actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cnv_activo',
            field=models.BooleanField(default=False, verbose_name='Activo CNV'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='creator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion_actual',
            field=models.CharField(max_length=100, null=True, verbose_name='Dirección Actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Soltero(a)'), ('2', 'Casado(a)'), ('3', 'Viudo(a)'), ('4', 'Divorciado(a)')], max_length=2, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Etnia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grado_instruccion',
            field=models.CharField(blank=True, choices=[('00', 'Sin instrucción'), ('01', 'Educación inicial'), ('02', 'Primaria completa'), ('03', 'Primaria incompleta'), ('04', 'Educación especial'), ('05', 'Secundaria completa'), ('06', 'Secundaria cncompleta'), ('07', 'Superior técnica completa'), ('08', 'Superior técnica incompleta'), ('09', 'Superior universitaria completa'), ('10', 'Superior universitaria incompleta'), ('11', 'Sin información'), ('12', 'No corresponde (menores de 3 años)')], max_length=2, null=True, verbose_name='Grado de instrucción'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hora_nacimiento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='latitud',
            field=models.CharField(default='-12.046374', max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='longitud',
            field=models.CharField(default='-77.0427934', max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='mensaje_personal',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='modifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacimiento_departamento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Departamento Nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacimiento_distrito',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Distrito Nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacimiento_pais',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Pais Nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacimiento_provincia',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Provincia Nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nº de Documento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_documento_cnv',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nº de Documento CNV'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_documento_madre',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nº de Documento Madre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('01', 'Profesional'), ('02', 'Empleado'), ('03', 'Comerciante'), ('04', 'Obrero'), ('05', 'Ama casa'), ('06', 'Estudiante'), ('07', 'Sin ocupacion'), ('08', 'Otro')], max_length=2, null=True, verbose_name='Ocupacion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='recibesms',
            field=models.BooleanField(default=False, verbose_name='Recibe SMS'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='referencia_actual',
            field=models.CharField(max_length=100, null=True, verbose_name='Referencia Actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='residencia_actual_departamento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Departamento Actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='residencia_actual_distrito',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Distrito Actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='residencia_actual_pais',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Pais Actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='residencia_actual_provincia',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Provincia Actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('2', 'Femenino'), ('1', 'Masculino')], max_length=2, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('00', 'NO SE CONOCE'), ('01', 'DNI/LE'), ('02', 'LM/BO'), ('03', 'CARNET DE EXTRAJERIA'), ('04', 'ACTA DE NACIMIENTO'), ('06', 'PASAPORTE'), ('07', 'DI DEL EXTRANJERO')], max_length=2, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento_madre',
            field=models.CharField(blank=True, choices=[('00', 'NO SE CONOCE'), ('01', 'DNI/LE'), ('02', 'LM/BO'), ('03', 'CARNET DE EXTRAJERIA'), ('04', 'ACTA DE NACIMIENTO'), ('06', 'PASAPORTE'), ('07', 'DI DEL EXTRANJERO')], max_length=2, null=True, verbose_name='Tipo de Documento Madre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='uid_cnv',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Nº de Documento'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together=set([('tipo_documento', 'numero_documento')]),
        ),
        migrations.AddField(
            model_name='pacientefinanciador',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Paciente'),
        ),
        migrations.AddField(
            model_name='pacientecontactofamiliar',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Paciente'),
        ),
        migrations.AddField(
            model_name='hce',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='pacientecontactofamiliar',
            unique_together=set([('paciente', 'tipo_documento', 'numero_documento')]),
        ),
        migrations.AlterUniqueTogether(
            name='hce',
            unique_together=set([('paciente', 'establecimiento')]),
        ),
    ]
