# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0002_auto_20170822_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATLugarAbordaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=50, verbose_name='Detalle')),
                ('fecha_abordaje', models.DateTimeField()),
                ('distrito_lugar_abordaje', models.CharField(max_length=20, verbose_name='Distrito de lugar de Abordaje')),
                ('nombre_lugar', models.CharField(blank=True, max_length=100, verbose_name='Nombre de lugar')),
                ('latitud', models.FloatField(max_length=100, verbose_name='Latitud')),
                ('longitud', models.FloatField(max_length=100, verbose_name='Longitud')),
            ],
            options={
                'ordering': ('lugar_abordaje',),
                'verbose_name_plural': 'Atenciones',
                'verbose_name': 'Atencion',
            },
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('ubigeo_departamento', models.CharField(blank=True, max_length=2, verbose_name='Ubigeo Departamento')),
                ('ubigeo_provincia', models.CharField(blank=True, max_length=4, verbose_name='Ubigeo Provincia')),
                ('ubigeo_distrito', models.CharField(blank=True, max_length=6, verbose_name='Ubigeo Distrito')),
                ('nombre_departamento', models.CharField(blank=True, max_length=30, verbose_name='Nombre de Departamento')),
                ('nombre_provincia', models.CharField(blank=True, max_length=30, verbose_name='Nombre de Provincia')),
                ('nombre_distrito', models.CharField(blank=True, max_length=30, verbose_name='Nombre de Distrito')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Brigadas',
                'verbose_name': 'Brigada',
            },
        ),
        migrations.CreateModel(
            name='LugarAbordaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True, verbose_name='Nombre lugar Abordaje')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado lugar de Abordaje')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Lugares abordaje',
                'verbose_name': 'Lugar abordaje',
            },
        ),
        migrations.CreateModel(
            name='PacienteLugarAbordaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_abordaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.ATLugarAbordaje')),
            ],
            options={
                'ordering': ('paciente',),
                'verbose_name_plural': 'Paciente lugar abordajes',
                'verbose_name': 'Paciente lugar abordaje ',
            },
        ),
        migrations.CreateModel(
            name='UsuarioBrigada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_name', models.CharField(max_length=15, verbose_name='Usuario login')),
                ('establecimiento', models.CharField(max_length=10, verbose_name='Establecimiento')),
                ('ups', models.CharField(max_length=10, verbose_name='UPS')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Brigada')),
            ],
            options={
                'ordering': ('usuario_name',),
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre social'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='poblacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Poblacion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_abordaje',
            field=models.CharField(choices=[('WEB', 'VIH'), ('MOVIL', 'APP_VIH')], default='WEB', max_length=10, verbose_name='Paciente abordaje'),
        ),
        migrations.AddField(
            model_name='poblacion',
            name='movil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Soltero(a)'), ('3', 'Casado(a)'), ('5', 'Conviviente'), ('2', 'Separado(a)'), ('4', 'Viudo(a)')], max_length=2, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='latitud',
            field=models.FloatField(default='-12.046374', max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='longitud',
            field=models.FloatField(default='-77.0427934', max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='pacientecontactofamiliar',
            name='celular',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pacientecontactofamiliar',
            name='sexo',
            field=models.CharField(blank=True, choices=[('2', 'Femenino'), ('1', 'Masculino')], max_length=12, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='pacientelugarabordaje',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Paciente'),
        ),
        migrations.AddField(
            model_name='atlugarabordaje',
            name='brigada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.Brigada'),
        ),
        migrations.AddField(
            model_name='atlugarabordaje',
            name='lugar_abordaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliacion.LugarAbordaje'),
        ),
    ]
