# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0003_auto_20171024_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sin_documento_estado',
            field=models.BooleanField(default=False, verbose_name='Estado sin documento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sin_documento_uuid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sin documento uuid'),
        ),
    ]
