# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0004_auto_20171107_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diresa', models.CharField(max_length=30, verbose_name='Diresa')),
                ('codigo_ipress', models.CharField(max_length=30, verbose_name='Código IPRESS')),
                ('categorizacion', models.CharField(max_length=30, verbose_name='Categorización')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo')),
                ('condicion', models.CharField(max_length=30, verbose_name='Condición')),
                ('establecimiento_salud', models.CharField(max_length=200, verbose_name='Establecimiento de Salud')),
                ('amp', models.CharField(max_length=30, verbose_name='AMP')),
                ('pediatria', models.CharField(max_length=20, verbose_name='Pediatria')),
                ('hepatitis_b', models.CharField(max_length=2, verbose_name='Hepatitis B')),
            ],
            options={
                'verbose_name_plural': 'Establecimientos',
                'verbose_name': 'Establecimiento',
            },
        ),
    ]
